package br.com.avaliacao2_lucas_siconeli.view;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import br.com.avaliacao2_lucas_siconeli.dto.ProfessorDTO;
import br.com.avaliacao2_lucas_siconeli.dto.CursoDTO;
import br.com.avaliacao2_lucas_siconeli.ctr.ProfessorCTR;
import br.com.avaliacao2_lucas_siconeli.ctr.CursoCTR;
        

public class CursoVIEW extends javax.swing.JInternalFrame {

    ProfessorDTO professorDTO = new ProfessorDTO();
    ProfessorCTR professorCTR = new ProfessorCTR();
    CursoDTO cursoDTO = new CursoDTO();
    CursoCTR cursoCTR = new CursoCTR();
    
    int gravar_alterar;
    
    ResultSet rs;
    DefaultTableModel model_jtl_consultar_curso;
    DefaultTableModel model_jtl_consultar_professor;
    
        
    /**
     * Creates new form cursoVIEW
     */
    public CursoVIEW() {
         initComponents();
        
        liberaCampos(false);
        
        liberaBotoes(true, false, false, false, true);
        model_jtl_consultar_professor = (DefaultTableModel) jtl_consultar_professor.getModel();
        model_jtl_consultar_curso = (DefaultTableModel) jtl_consultar_curso.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome_cur = new javax.swing.JTextField();
        desc_cur = new javax.swing.JTextField();
        cod_cur = new javax.swing.JTextField();
        p_custo_cur = new javax.swing.JTextField();
        pesquisa_nome_professor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtl_consultar_professor = new javax.swing.JTable();
        btnPesquisarProfessor = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtl_consultar_curso = new javax.swing.JTable();
        pesquisa_nome_cur = new javax.swing.JTextField();
        brnPesquisarCurso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        nome_cur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_curActionPerformed(evt);
            }
        });

        cod_cur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_curActionPerformed(evt);
            }
        });

        p_custo_cur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_custo_curActionPerformed(evt);
            }
        });

        jtl_consultar_professor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        jScrollPane1.setViewportView(jtl_consultar_professor);

        btnPesquisarProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/avaliacao2_lucas_siconeli/view/imagens/pesquisar.png"))); // NOI18N
        btnPesquisarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProfessorActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/avaliacao2_lucas_siconeli/view/imagens/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/avaliacao2_lucas_siconeli/view/imagens/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/avaliacao2_lucas_siconeli/view/imagens/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/avaliacao2_lucas_siconeli/view/imagens/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/avaliacao2_lucas_siconeli/view/imagens/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jtl_consultar_curso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        jtl_consultar_curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtl_consultar_cursoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtl_consultar_curso);

        pesquisa_nome_cur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_nome_curActionPerformed(evt);
            }
        });

        brnPesquisarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/avaliacao2_lucas_siconeli/view/imagens/pesquisar.png"))); // NOI18N
        brnPesquisarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnPesquisarCursoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Código:");

        jLabel4.setText("P.Custo:");

        jLabel6.setText("Nome:");

        jLabel7.setText("Professor");

        jLabel8.setText("CURSO");

        jLabel9.setText("Consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome_cur)
                                    .addComponent(desc_cur)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pesquisa_nome_professor, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisarProfessor))
                                    .addComponent(cod_cur)
                                    .addComponent(p_custo_cur)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pesquisa_nome_cur, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(brnPesquisarCurso))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_cur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(desc_cur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cod_cur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(brnPesquisarCurso)
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p_custo_cur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(pesquisa_nome_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisarProfessor)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisa_nome_cur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_curActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_curActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_curActionPerformed

    private void cod_curActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_curActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_curActionPerformed

    private void pesquisa_nome_curActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_nome_curActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisa_nome_curActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        liberaCampos(true);
        liberaBotoes(false, true, true, false, true);
        gravar_alterar = 1;// TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProfessorActionPerformed
        preencheTabelaprofessor(pesquisa_nome_professor.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarProfessorActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(gravar_alterar==1){
            gravar();
            gravar_alterar=0;
        }
        else{
            if(gravar_alterar==2){
                alterar();
                gravar_alterar=0;
            }
            else{
                JOptionPane.showMessageDialog(null, "erro no sistema!!!");
            }
        }
        
        limpaCampos();
        liberaCampos(false);
        liberaBotoes(true, false, false, false, true);
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void brnPesquisarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnPesquisarCursoActionPerformed
        preencheTabelacurso(pesquisa_nome_cur.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_brnPesquisarCursoActionPerformed

    private void jtl_consultar_cursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtl_consultar_cursoMouseClicked
        preencheCamposCurso(Integer.parseInt(String.valueOf(
        jtl_consultar_curso.getValueAt(
        jtl_consultar_curso.getSelectedRow(), 0))));
        liberaBotoes(false, true, true, true, true);// TODO add your handling code here:
    }//GEN-LAST:event_jtl_consultar_cursoMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluir();
        limpaCampos();
        liberaCampos(false);
        liberaBotoes(true, false, false, false, true);
        model_jtl_consultar_curso.setNumRows(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCampos();
        liberaCampos(false);
        model_jtl_consultar_curso.setNumRows(0);
        liberaBotoes(true, false, false, false, true);
        gravar_alterar = 0;        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void p_custo_curActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_custo_curActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_custo_curActionPerformed

    
    public void setPosicao(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    private void gravar() {
    try {
        cursoDTO.setNome_cur(nome_cur.getText());
        cursoDTO.setDesc_cur(desc_cur.getText());
        cursoDTO.setCod_bar_cur(cod_cur.getText());
        cursoDTO.setP_custo_cur(Double.parseDouble(p_custo_cur.getText()));
        professorDTO.setId_prof(Integer.parseInt(String.valueOf(
                jtl_consultar_professor.getValueAt(
                jtl_consultar_professor.getSelectedRow(), 0))));
        
        JOptionPane.showMessageDialog(null,
                cursoCTR.inserirCurso(cursoDTO, professorDTO));
    } catch (Exception e) {
        System.out.println("Erro ao Gravar: " + e.getMessage());
    }
}
    private void alterar() {
    try {
        cursoDTO.setNome_cur(nome_cur.getText());
        cursoDTO.setDesc_cur(desc_cur.getText());
        cursoDTO.setCod_bar_cur(cod_cur.getText());
        cursoDTO.setP_custo_cur(Double.parseDouble(p_custo_cur.getText()));
        professorDTO.setId_prof(Integer.parseInt(String.valueOf(
                jtl_consultar_professor.getValueAt(
                jtl_consultar_professor.getSelectedRow(), 0))));
        
        JOptionPane.showMessageDialog(null,
                cursoCTR.alterarCurso(cursoDTO, professorDTO));
    } catch (Exception e) {
        System.out.println("Erro ao Gravar: " + e.getMessage());
    }
}
    
    private void excluir(){
    if(JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir o curso?", "Aviso", 
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,
                    cursoCTR.excluirCurso(cursoDTO));
    }
}
    
    private void liberaCampos(boolean a) {
    nome_cur.setEnabled(a);
    desc_cur.setEnabled(a);
    cod_cur.setEnabled(a);
    p_custo_cur.setEnabled(a);
    pesquisa_nome_professor.setEnabled(a);
    btnPesquisarProfessor.setEnabled(a);
    jtl_consultar_professor.setEnabled(a);
}
    
    private void liberaBotoes(boolean a, boolean b, boolean c, boolean d, boolean e){
    btnNovo.setEnabled(a);
    btnSalvar.setEnabled(b);
    btnCancelar.setEnabled(c);
    btnExcluir.setEnabled(d);
    btnSair.setEnabled(e);
}// fecha o método liberaBotoes
    
    private void limpaCampos() {
    nome_cur.setText("");
    desc_cur.setText("");
    cod_cur.setText("");
    p_custo_cur.setText("");
    pesquisa_nome_professor.setText("");
    model_jtl_consultar_professor.setNumRows(0);
}
    
    private void preencheTabelacurso(String nome_cur){
    try{
        model_jtl_consultar_curso.setNumRows(0);
        cursoDTO.setNome_cur(nome_cur);
        rs = cursoCTR.consultarCurso(cursoDTO, 1);
        while(rs.next()){
            model_jtl_consultar_curso.addRow(new Object[]{
                rs.getString("id_cur"),
                rs.getString("nome_cur")
            });
        }
    }catch(Exception e){
        System.out.println("Erro ao preencheTabela"+e.getMessage());
    }finally{
        professorCTR.CloseDB();
    }
}

    private void preencheCamposCurso(int id_cur) {
    try {
        cursoDTO.setId_cur(id_cur);
        rs = cursoCTR.consultarCurso(cursoDTO, 2);
        if (rs.next()) {
            limpaCampos();
            nome_cur.setText(rs.getString("nome_cur"));
            desc_cur.setText(rs.getString("desc_cur"));
            cod_cur.setText(rs.getString("cod_bar_cur"));
            p_custo_cur.setText(rs.getString("p_custo_cur"));
            
            
            model_jtl_consultar_professor.setNumRows(0);
            model_jtl_consultar_professor.addRow(new Object[]{rs.getInt("id_prof"), rs.getString("nome_prof"),});
            jtl_consultar_professor.setRowSelectionInterval(0, 0);
            
            gravar_alterar = 2;
            liberaCampos(true);
        }
    } catch (Exception e) {
        System.out.println("Erro ao preencheCamposCurso" + e.getMessage());
    } finally {
        cursoCTR.CloseDB();
    }
}

    private void preencheTabelaprofessor(String nome_prof){
    try{
        model_jtl_consultar_professor.setNumRows(0);
        professorDTO.setNome_prof(nome_prof);
        rs = professorCTR.consultarProfessor(professorDTO, 1);
        while(rs.next()){
            model_jtl_consultar_professor.addRow(new Object[]{
                rs.getString("id_prof"),
                rs.getString("nome_prof")
            });
        }
    }catch(Exception e){
        System.out.println("Erro ao preencheTabelaProfessor"+e.getMessage());
    }finally{
        professorCTR.CloseDB();
    }
}
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnPesquisarCurso;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisarProfessor;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField cod_cur;
    private javax.swing.JTextField desc_cur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtl_consultar_curso;
    private javax.swing.JTable jtl_consultar_professor;
    private javax.swing.JTextField nome_cur;
    private javax.swing.JTextField p_custo_cur;
    private javax.swing.JTextField pesquisa_nome_cur;
    private javax.swing.JTextField pesquisa_nome_professor;
    // End of variables declaration//GEN-END:variables
}
